import type { ReactNode } from "react";
import type { LucideIcon } from "lucide-react";
import { AlertTriangle, CheckCircle2, CircleDashed, CircleHelp, FileJson2, FlaskConical, Globe2, Info, KeyRound, LoaderCircle, ShieldAlert, ShieldCheck, Unplug, XCircle } from "lucide-react";

export function PageHeading({eyebrow,title,description,actions}:{eyebrow:string;title:string;description:string;actions?:ReactNode}){return <div className="page-heading"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p className="subtitle">{description}</p></div>{actions&&<div className="toolbar page-heading-actions">{actions}</div>}</div>}
export function Card({title,description,action,children,className=""}:{title?:string;description?:string;action?:ReactNode;children:ReactNode;className?:string}){return <section className={`card ${className}`}>{title&&<div className="card-header"><div><h2>{title}</h2>{description&&<p className="subtitle" style={{fontSize:10,marginTop:4}}>{description}</p>}</div>{action}</div>}<div className={title?"card-content":""}>{children}</div></section>}
const badgeIcons:Record<string,LucideIcon>={completed:CheckCircle2,partial:CircleDashed,running:LoaderCircle,failed:XCircle,"not-assessed":CircleHelp,"authentication-required":KeyRound,"connection-failed":Unplug,connected:CheckCircle2,live:Globe2,sample:FlaskConical,offline:FileJson2,critical:ShieldAlert,high:ShieldAlert,medium:AlertTriangle,low:ShieldCheck,info:Info};
export function StatusBadge({value}:{value:string}){const normalized=value.toLowerCase();const Icon=badgeIcons[normalized];return <span className={`badge ${normalized}`} data-status={normalized}>{Icon&&<Icon size={10}/>} {value.replaceAll("-"," ")}</span>}
export function assessmentDisplayStatus(status:string,connectionStatus?:string){return connectionStatus==="authentication-required"||connectionStatus==="connection-failed"?connectionStatus:status}
export function AssessmentStatusBadge({status,connectionStatus}:{status:string;connectionStatus?:string}){return <StatusBadge value={assessmentDisplayStatus(status,connectionStatus)}/>}
export function InfoTip({text,label="More information"}:{text:string;label?:string}){return <span className="info-tip" tabIndex={0} aria-label={`${label}: ${text}`}><CircleHelp size={13}/><span role="tooltip">{text}</span></span>}
export function Score({value,size=150}:{value:number;size?:number}){return <div className="score-ring" style={{"--score":Math.max(0,Math.min(100,value)),width:size,height:size} as React.CSSProperties}><strong>{value}</strong><small>out of 100</small></div>}
export function LoadingCards(){return <div className="grid metrics-grid" role="status" aria-live="polite" aria-busy="true"><span className="sr-only">Loading assessment data</span>{[1,2,3,4].map(i=><div key={i} className="card metric" aria-hidden="true"><div className="skeleton" style={{width:"45%"}}/><div className="skeleton" style={{width:"65%",height:32,marginTop:16}}/></div>)}</div>}
