package reporting

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"html/template"
	"sort"
	"strings"

	"github.com/agntid/observatory/api/internal/domain"
	"github.com/agntid/observatory/api/internal/ports"
)

type Generator struct{ Store ports.ArtifactStore }

func (g Generator) Generate(ctx context.Context, a *domain.Assessment) ([]domain.Artifact, error) {
	canonical, err := json.MarshalIndent(a, "", "  ")
	if err != nil {
		return nil, err
	}
	sarif, err := sarifJSON(a)
	if err != nil {
		return nil, err
	}
	specs := []struct {
		name, contentType string
		body              []byte
	}{
		{"assessment.json", "application/json", canonical},
		{"executive-summary.md", "text/markdown; charset=utf-8", []byte(executiveMarkdown(a))},
		{"technical-report.md", "text/markdown; charset=utf-8", []byte(technicalMarkdown(a))},
		{"assessment.sarif", "application/sarif+json", sarif},
	}
	artifacts := []domain.Artifact{}
	for _, spec := range specs {
		artifact, putErr := g.Store.Put(ctx, a.ID, spec.name, spec.contentType, bytes.NewReader(spec.body))
		if putErr != nil {
			return nil, putErr
		}
		artifacts = append(artifacts, artifact)
	}
	for _, spec := range []struct{ name, kind string }{{"executive-summary.html", "executive"}, {"technical-report.html", "technical"}} {
		body, renderErr := renderHTML(a, spec.kind)
		if renderErr != nil {
			return nil, renderErr
		}
		artifact, putErr := g.Store.Put(ctx, a.ID, spec.name, "text/html; charset=utf-8", bytes.NewReader(body))
		if putErr != nil {
			return nil, putErr
		}
		artifacts = append(artifacts, artifact)
	}
	return artifacts, nil
}

func executiveMarkdown(a *domain.Assessment) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# AgntID Observatory Executive Assessment\n\n**Target:** %s  \n**Overall readiness:** %d/100  \n**Assessment coverage:** %.0f%%  \n\n## Executive summary\n\n%s\n\n## Scorecard\n\n", a.Target.URL, a.Scorecard.Overall, a.Scorecard.Coverage, a.ExecutiveSummary)
	for _, d := range orderedDimensions(a) {
		fmt.Fprintf(&b, "- **%s:** %d/100 (%.0f%% coverage)\n", d.Name, d.Score, d.Coverage)
	}
	fmt.Fprintf(&b, "\n## Identity and policy snapshot\n\n- Connected identity profiles: **%d**\n- Anonymous tools advertised: **%d**\n- Catalog separation: **%s**\n", a.IdentityExposure.ComparedProfiles, a.IdentityExposure.AnonymousToolCount, catalogComparison(a.IdentityExposure.ComparedProfiles, a.IdentityExposure.PrivilegeSeparationObserved))
	if a.OAuth.Protected {
		fmt.Fprintf(&b, "- OAuth protected: **Yes** — resource metadata **%s**, PKCE S256 **%s**, DCR **%s**\n", passFail(a.OAuth.ResourceMetadataValid), passFail(a.OAuth.PKCES256), available(a.OAuth.DCRSupported))
	}
	for _, p := range a.PolicySimulation.Profiles {
		fmt.Fprintf(&b, "- **%s:** %d visible, %d hidden, %d requiring approval\n", p.Name, p.VisibleCount, p.HiddenCount, p.ApprovalCount)
	}
	if len(a.RiskChains) > 0 {
		b.WriteString("\n## Capability risk chains\n\n")
		for _, chain := range a.RiskChains {
			fmt.Fprintf(&b, "- **%s (%s):** %s\n", chain.Title, strings.ToUpper(chain.Severity), chain.Description)
		}
	}
	fmt.Fprintf(&b, "\n## Catalog and content governance\n\n- Catalog baseline compared: **%s**\n- Catalog changes: **%d added, %d removed, %d modified**\n- Metadata integrity signals: **%d**\n- Average tool contract readiness: **%d/100** (%.0f%% observable coverage)\n", yesNo(a.CatalogDrift.Compared), a.CatalogDrift.Added, a.CatalogDrift.Removed, a.CatalogDrift.Modified, len(a.ContentIntegrity.Signals), a.Readiness.AverageScore, a.Readiness.Coverage)
	b.WriteString("\n## Priority recommendations\n\n")
	for i, r := range a.Recommendations {
		if i >= 5 {
			break
		}
		fmt.Fprintf(&b, "%d. **%s** — %s\n", i+1, r.Title, r.Detail)
	}
	b.WriteString("\n---\nGenerated by AgntID Observatory. Results distinguish measured, inferred, sampled, and unavailable evidence.\n")
	return b.String()
}

func technicalMarkdown(a *domain.Assessment) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# Technical MCP Assessment\n\n%s\n\n## Server profile\n\n- Server: %s %s\n- Protocol: %s\n- Transport: %s\n- Tools: %d\n- Prompts: %d\n- Resources: %d\n\n", a.TechnicalSummary, a.Server.Name, a.Server.Version, a.Server.ProtocolVersion, a.Server.Transport, a.Server.ToolCount, a.Server.PromptCount, a.Server.ResourceCount)
	b.WriteString("## OAuth security posture\n\n")
	if !a.OAuth.Protected {
		b.WriteString("OAuth protection was not required by the anonymous initialization probe.\n\n")
	} else {
		fmt.Fprintf(&b, "| Control | Result |\n|---|---|\n| Protected-resource metadata | %s |\n| Authorization-server metadata | %s |\n| PKCE S256 | %s |\n| Dynamic Client Registration | %s |\n| Header bearer method | %s |\n| Scopes advertised | %s |\n\n", passFail(a.OAuth.ResourceMetadataValid), passFail(a.OAuth.AuthorizationServerMetadataValid), passFail(a.OAuth.PKCES256), available(a.OAuth.DCRSupported), passFail(a.OAuth.HeaderBearerSupported), yesNo(len(a.OAuth.Scopes) > 0))
		fmt.Fprintf(&b, "- Issuer: %s\n- Resource: %s\n- Registration method: %s\n- Interactive OAuth identities: %s\n\n", fallback(a.OAuth.Issuer, "Unavailable"), fallback(a.OAuth.Resource, "Unavailable"), fallback(a.OAuth.RegistrationMethod, "Not completed"), fallback(strings.Join(a.OAuth.AuthorizedIdentities, ", "), "Not completed during this scan"))
	}
	b.WriteString("## Findings\n\n")
	for _, f := range a.Findings {
		fmt.Fprintf(&b, "### [%s] %s — %s\n\n%s\n\n**Evidence:** %s, %.0f%% confidence · **Affected tools:** %d\n\n**Why it matters:** %s\n\n**Recommendation:** %s\n\n", strings.ToUpper(f.Severity), f.RuleID, f.Title, f.Description, f.Provenance, f.Confidence*100, len(f.ToolNames), f.WhyItMatters, f.Recommendation.Detail)
		if f.Replay != nil {
			fmt.Fprintf(&b, "#### Illustrative policy replay — %s\n\n**Observed:** %s\n\n1. **Plausible trigger:** %s\n2. **Without explicit policy:** %s\n3. **AgntID decision:** %s\n4. **Protected outcome:** %s\n\n_%s_\n\n", f.Replay.Title, f.Replay.Observed, f.Replay.Trigger, f.Replay.UnprotectedPath, f.Replay.AgntIDDecision, f.Replay.ProtectedOutcome, f.Replay.Disclaimer)
		}
	}
	b.WriteString("## Identity exposure\n\nTool visibility is measured from metadata returned to each supplied identity. It does not prove that a visible tool can be executed.\n\n")
	if len(a.IdentityExposure.Profiles) == 0 {
		b.WriteString("No comparable identity metadata was available.\n\n")
	} else {
		b.WriteString("| Identity | Authentication | Status | Tools |\n|---|---|---:|---:|\n")
		for _, p := range a.IdentityExposure.Profiles {
			fmt.Fprintf(&b, "| %s | %s | %s | %d |\n", p.Label, p.Authentication, p.Status, p.ToolCount)
		}
		b.WriteString("\n")
	}
	b.WriteString("## Tool intelligence\n\n| Tool | Operation | Effects | Sensitivity | Blast radius | Visible to | Risk |\n|---|---|---|---|---|---|---|\n")
	for _, tool := range a.Tools {
		fmt.Fprintf(&b, "| %s | %s | %s | %s | %s | %s | %s |\n", tool.Name, tool.Classification.OperationType, strings.Join(tool.Classification.Effects, ", "), tool.Classification.Sensitivity, tool.Classification.BlastRadius, strings.Join(tool.VisibleTo, ", "), tool.Risk)
	}
	b.WriteString("\n## OWASP-aligned input and output trust boundaries\n\nThese discovery-time signals identify where model-generated values or untrusted tool results can cross a sensitive boundary. They do not prove that server-side validation or runtime enforcement is absent.\n\n| Tool | Agent-controlled input boundary | Output trust |\n|---|---|---|\n")
	for _, tool := range a.Tools {
		fmt.Fprintf(&b, "| %s | %s | %s |\n", tool.Name, inputRiskSummary(tool.Schema.InputRisks), outputTrustSummary(tool))
	}
	b.WriteString("\n## Policy preview\n\n")
	for _, p := range a.PolicySimulation.Profiles {
		fmt.Fprintf(&b, "- **%s:** %d visible, %d hidden, %d requiring approval\n", p.Name, p.VisibleCount, p.HiddenCount, p.ApprovalCount)
	}
	if a.PolicySimulation.Disclaimer != "" {
		fmt.Fprintf(&b, "\n_%s_\n", a.PolicySimulation.Disclaimer)
	}
	if len(a.RiskChains) > 0 {
		b.WriteString("\n## Capability risk chains\n\n")
		for _, chain := range a.RiskChains {
			fmt.Fprintf(&b, "### [%s] %s\n\n%s\n\n**Tools:** %s  \n**Signals:** %s\n\n", strings.ToUpper(chain.Severity), chain.Title, chain.Description, strings.Join(chain.ToolNames, ", "), strings.Join(chain.Signals, ", "))
		}
	}
	b.WriteString("## Catalog drift\n\n")
	b.WriteString("Catalog drift compares the current advertised tool catalog with the latest completed assessment of the same target. It detects tools that appeared, disappeared, or changed. Changes can come from a deployment, dynamic server configuration, SDK updates, or different identity visibility.\n\n**Why it matters:** a previously reviewed tool name can acquire different inputs, behavior, or risk while an old policy decision remains in place.\n\n")
	if !a.CatalogDrift.Compared {
		b.WriteString("No prior completed assessment of this target was available; the current fingerprint can be used as a baseline.\n\n")
	} else if len(a.CatalogDrift.Changes) == 0 {
		b.WriteString("The advertised catalog matches the prior assessment.\n\n")
	} else {
		b.WriteString("| Tool | Change | Severity | Fields | Policy impact |\n|---|---|---|---|---|\n")
		for _, change := range a.CatalogDrift.Changes {
			fmt.Fprintf(&b, "| %s | %s | %s | %s | %s |\n", change.ToolName, change.ChangeType, change.Severity, strings.Join(change.Fields, ", "), change.PolicyImpact)
		}
		b.WriteString("\n")
	}
	b.WriteString("## Metadata content integrity\n\n")
	b.WriteString("This check reviews text an AI may read before any tool is called—including server instructions, tool and schema descriptions, prompts, and resource descriptions—for patterns associated with instruction override, credential disclosure, tool redirection, or unintended data transfer. It is indicator-based and does not produce a safety score.\n\n")
	if len(a.ContentIntegrity.Signals) == 0 {
		fmt.Fprintf(&b, "**Result:** No deterministic warning patterns were found across **%d advertised metadata surfaces**. This is not proof that all content or runtime behavior is safe.\n\n", a.ContentIntegrity.ItemsScanned)
	} else {
		for _, signal := range a.ContentIntegrity.Signals {
			fmt.Fprintf(&b, "### [%s] %s — %s\n\n%s\n\n**Matched excerpt:** `%s`\n\n**Recommendation:** %s\n\n", strings.ToUpper(signal.Severity), signal.SurfaceID, signal.Title, signal.Summary, signal.MatchedText, signal.Recommendation)
		}
	}
	b.WriteString("## Per-tool contract readiness\n\nContract readiness estimates how precisely each advertised tool can be selected, validated, and governed from its metadata. **Score** is declaration quality (0–100) based on observed checks. **Coverage** is the percentage of applicable checks that metadata could prove; lower coverage means uncertainty, not automatic failure. **Grade** summarizes score: Strong 85–100, Developing 70–84, Needs work below 70.\n\n| Tool | Score | Coverage | Grade |\n|---|---:|---:|---|\n")
	for _, tool := range a.Readiness.Tools {
		fmt.Fprintf(&b, "| %s | %d | %.0f%% | %s |\n", tool.ToolName, tool.Score, tool.Coverage, tool.Grade)
	}
	fmt.Fprintf(&b, "\n_%s_\n\n", a.Readiness.Disclaimer)
	b.WriteString("## Assessment timeline\n\n")
	for _, run := range a.EngineRuns {
		fmt.Fprintf(&b, "- %s: %s — %s\n", run.Name, run.Status, run.Message)
	}
	return b.String()
}

func sarifJSON(a *domain.Assessment) ([]byte, error) {
	rules := map[string]any{}
	results := []any{}
	level := func(severity string) string {
		switch severity {
		case "critical", "high":
			return "error"
		case "medium":
			return "warning"
		default:
			return "note"
		}
	}
	add := func(id, title, severity, message, uri string, properties map[string]any) {
		rules[id] = map[string]any{"id": id, "name": title, "shortDescription": map[string]any{"text": title}}
		result := map[string]any{"ruleId": id, "level": level(severity), "message": map[string]any{"text": message}, "properties": properties}
		if uri != "" {
			result["locations"] = []any{map[string]any{"physicalLocation": map[string]any{"artifactLocation": map[string]any{"uri": uri}}}}
		}
		results = append(results, result)
	}
	for _, finding := range a.Findings {
		add(finding.RuleID, finding.Title, finding.Severity, finding.Description, "", map[string]any{"category": finding.Category, "provenance": finding.Provenance, "confidence": finding.Confidence})
	}
	for _, signal := range a.ContentIntegrity.Signals {
		add(signal.RuleID, signal.Title, signal.Severity, signal.Summary, "mcp-metadata://"+signal.SurfaceKind+"/"+signal.SurfaceID, map[string]any{"matchedText": signal.MatchedText, "confidence": signal.Confidence, "recommendation": signal.Recommendation})
	}
	for _, change := range a.CatalogDrift.Changes {
		add("CATALOG-DRIFT-"+strings.ToUpper(change.ChangeType), "Catalog "+change.ChangeType, change.Severity, change.Summary, "mcp-tool://"+change.ToolName, map[string]any{"fields": change.Fields, "policyImpact": change.PolicyImpact, "baselineAssessmentId": a.CatalogDrift.BaselineAssessmentID})
	}
	descriptors := []any{}
	keys := make([]string, 0, len(rules))
	for key := range rules {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	for _, key := range keys {
		descriptors = append(descriptors, rules[key])
	}
	doc := map[string]any{"version": "2.1.0", "$schema": "https://json.schemastore.org/sarif-2.1.0.json", "runs": []any{map[string]any{"tool": map[string]any{"driver": map[string]any{"name": "AgntID Observatory", "semanticVersion": "0.3.0", "informationUri": "https://agntid.ai", "rules": descriptors}}, "automationDetails": map[string]any{"id": a.ID}, "results": results}}}
	return json.MarshalIndent(doc, "", "  ")
}

func yesNo(v bool) string {
	if v {
		return "Yes"
	}
	return "No"
}

func catalogComparison(comparedProfiles int, separationObserved bool) string {
	if comparedProfiles < 2 {
		return "Not enough connected profiles"
	}
	if separationObserved {
		return "Different catalogs observed"
	}
	return "Equivalent catalogs observed"
}

func passFail(v bool) string {
	if v {
		return "Verified"
	}
	return "Not verified"
}

func available(v bool) string {
	if v {
		return "Available"
	}
	return "Not advertised"
}

func fallback(value, alternative string) string {
	if strings.TrimSpace(value) == "" {
		return alternative
	}
	return value
}

func inputRiskSummary(risks []domain.InputRisk) string {
	if len(risks) == 0 {
		return "No high-impact field inferred"
	}
	values := make([]string, 0, len(risks))
	for _, risk := range risks {
		constraint := "unconstrained"
		if risk.Constrained {
			constraint = "declared constraint"
		}
		values = append(values, fmt.Sprintf("%s %s (%s)", risk.Kind, risk.Path, constraint))
	}
	return strings.Join(values, "; ")
}

func outputTrustSummary(tool domain.ToolProfile) string {
	if tool.Schema.HasOutputSchema {
		return "Output schema advertised"
	}
	if (tool.Annotations.OpenWorldHint != nil && *tool.Annotations.OpenWorldHint) || (tool.Classification.IsDiscover && tool.Classification.ExecutionSurface == "REMOTE_API") || containsValue(tool.Classification.Effects, "EXTERNAL_SERVICE_CALL") || tool.Classification.ExecutionSurface == "BROWSER_SESSION" {
		return "No output schema; remote or open-world result inferred"
	}
	return "No output schema advertised"
}

func containsValue(values []string, wanted string) bool {
	for _, value := range values {
		if value == wanted {
			return true
		}
	}
	return false
}

var htmlTemplate = template.Must(template.New("report").Funcs(template.FuncMap{"upper": strings.ToUpper, "join": func(v []string) string { return strings.Join(v, ", ") }, "yesno": yesNo, "catalogcomparison": catalogComparison, "inputrisks": inputRiskSummary, "outputtrust": outputTrustSummary}).Parse(`<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>AgntID Observatory Report</title>
<style>:root{color-scheme:light;--ink:#102238;--muted:#607086;--line:#dbe3ec;--brand:#3764f4;--surface:#f5f7fb;--good:#177a55;--good-bg:#eaf8f1;--warn-bg:#fff7e8}*{box-sizing:border-box}body{margin:0;font:15px/1.55 Inter,system-ui,sans-serif;color:var(--ink);background:var(--surface)}main{max-width:1050px;margin:40px auto;background:white;padding:48px;border:1px solid var(--line);border-radius:18px}header{display:flex;justify-content:space-between;align-items:center;border-bottom:1px solid var(--line);padding-bottom:24px}.brand{font-weight:800;letter-spacing:-.03em}.eyebrow{color:var(--brand);font-size:12px;text-transform:uppercase;letter-spacing:.12em}.hero{display:grid;grid-template-columns:1fr 180px;gap:30px;padding:42px 0}.score{display:grid;place-items:center;border:12px solid #dce4ff;border-top-color:var(--brand);border-radius:50%;width:150px;height:150px;font-size:38px;font-weight:800}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.card{padding:18px;border:1px solid var(--line);border-radius:12px}.card strong{font-size:24px;display:block}.card small{color:var(--muted)}.finding{border-left:4px solid #f59e0b;padding:8px 18px;margin:18px 0}.high,.critical{border-color:#e54d5d}.low{border-color:#3ca36c}.muted{color:var(--muted)}table{width:100%;border-collapse:collapse}td,th{text-align:left;border-bottom:1px solid var(--line);padding:10px;vertical-align:top}.section{margin-top:34px}.section-lead{max-width:820px;color:var(--muted);margin:0 0 12px}.why{border-left:3px solid var(--brand);background:#f4f6ff;padding:11px 14px;margin:12px 0;border-radius:0 8px 8px 0}.result{border:1px solid var(--line);border-radius:10px;padding:14px 16px;margin:14px 0}.result.good{background:var(--good-bg);border-color:#bce7d2}.result.good strong{color:var(--good);display:block}.legend{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin:14px 0}.legend>div{border:1px solid var(--line);border-radius:9px;padding:11px}.legend strong{display:block;font-size:13px}.legend span{color:var(--muted);font-size:12px}.change{border:1px solid var(--line);border-radius:12px;padding:15px 17px;margin:10px 0}.change-head{display:flex;align-items:center;gap:8px;flex-wrap:wrap}.change-head h3{margin:0 auto 0 0}.badge{display:inline-block;padding:3px 8px;border-radius:999px;background:#edf1ff;color:var(--brand);font-size:11px}.badge.severity{background:var(--warn-bg);color:#995900}.pill{display:inline-block;padding:3px 8px;border-radius:999px;background:#edf1ff;color:var(--brand);font-size:12px;margin:2px}.chain{border:1px solid var(--line);border-radius:12px;padding:16px;margin:10px 0}.report-replay{margin-top:12px;border:1px solid var(--line);border-radius:10px;background:var(--surface);overflow:hidden}.report-replay summary{cursor:pointer;padding:11px 13px;color:var(--brand);font-weight:700}.report-replay[open] summary{border-bottom:1px solid var(--line)}.report-replay>div,.report-replay>ol,.report-replay>p{margin-left:13px;margin-right:13px}.report-replay ol{padding-left:20px}.report-replay li{margin:8px 0}@media(max-width:760px){main{margin:0;padding:24px}.hero{grid-template-columns:1fr}.grid,.legend{grid-template-columns:1fr 1fr}}@media print{body{background:#fff}main{margin:0;border:0}.report-replay>summary{display:none}.report-replay>*{display:block}}</style></head>
<body><main><header><div><div class="brand">AgntID Observatory</div><div class="muted">Powered by AgntID</div></div><div class="eyebrow">{{.Mode}} assessment</div></header>
<section class="hero"><div><div class="eyebrow">Executive readiness assessment</div><h1>{{.Target.URL}}</h1><p class="muted">{{.ExecutiveSummary}}</p></div><div class="score">{{.Scorecard.Overall}}</div></section>
<section class="grid">{{range .Dimensions}}<div class="card"><span class="muted">{{.Name}}</span><strong>{{.Score}}</strong><small>{{printf "%.0f" .Coverage}}% coverage</small></div>{{end}}</section>
<section class="section"><h2>Identity and policy snapshot</h2><div class="grid"><div class="card"><span class="muted">Connected profiles</span><strong>{{.Detail.IdentityExposure.ComparedProfiles}}</strong></div><div class="card"><span class="muted">Anonymous tools</span><strong>{{.Detail.IdentityExposure.AnonymousToolCount}}</strong></div><div class="card"><span class="muted">Catalog separation</span><strong>{{catalogcomparison .Detail.IdentityExposure.ComparedProfiles .Detail.IdentityExposure.PrivilegeSeparationObserved}}</strong></div><div class="card"><span class="muted">Potential chains</span><strong>{{len .Detail.RiskChains}}</strong></div></div></section>
{{if .Detail.OAuth.Protected}}<section class="section"><h2>OAuth security posture</h2><div class="grid"><div class="card"><span class="muted">Resource metadata</span><strong>{{if .Detail.OAuth.ResourceMetadataValid}}Verified{{else}}Review{{end}}</strong></div><div class="card"><span class="muted">PKCE S256</span><strong>{{if .Detail.OAuth.PKCES256}}Verified{{else}}Review{{end}}</strong></div><div class="card"><span class="muted">DCR</span><strong>{{if .Detail.OAuth.DCRSupported}}Available{{else}}Not advertised{{end}}</strong></div><div class="card"><span class="muted">OAuth identities</span><strong>{{len .Detail.OAuth.AuthorizedIdentities}}</strong></div></div><p class="muted">Issuer: {{.Detail.OAuth.Issuer}} · Resource: {{.Detail.OAuth.Resource}}</p></section>{{end}}
<section class="section"><h2>Catalog and content governance</h2><div class="grid"><div class="card"><span class="muted">Catalog changes</span><strong>{{len .Detail.CatalogDrift.Changes}}</strong><small>Since the prior scan</small></div><div class="card"><span class="muted">Integrity signals</span><strong>{{len .Detail.ContentIntegrity.Signals}}</strong><small>Across {{.Detail.ContentIntegrity.ItemsScanned}} metadata surfaces</small></div><div class="card"><span class="muted">Contract readiness</span><strong>{{.Detail.Readiness.AverageScore}}/100</strong><small>Average declaration quality</small></div><div class="card"><span class="muted">Contract coverage</span><strong>{{printf "%.0f" .Detail.Readiness.Coverage}}%</strong><small>Applicable checks observed</small></div></div></section>
{{if .Detail.PolicySimulation.Profiles}}<section class="section"><h2>Illustrative AgntID policy profiles</h2><table><thead><tr><th>Profile</th><th>Visible</th><th>Hidden</th><th>Approval</th></tr></thead><tbody>{{range .Detail.PolicySimulation.Profiles}}<tr><td>{{.Name}}</td><td>{{.VisibleCount}}</td><td>{{.HiddenCount}}</td><td>{{.ApprovalCount}}</td></tr>{{end}}</tbody></table><p class="muted">{{.Detail.PolicySimulation.Disclaimer}}</p></section>{{end}}
<h2>Priority findings</h2>{{range .Detail.Findings}}<article class="finding {{.Severity}}"><div class="eyebrow">{{upper .Severity}} · {{.Classification}}</div><h3>{{.Title}}</h3><p>{{.Description}}</p><p><strong>Recommendation:</strong> {{.Recommendation.Detail}}</p>{{if and (eq $.Kind "technical") .Replay}}<details class="report-replay"><summary>View illustrative policy replay</summary><div class="result"><strong>Observed in this assessment</strong><br>{{.Replay.Observed}}</div><ol><li><strong>Plausible trigger:</strong> {{.Replay.Trigger}}</li><li><strong>Without explicit policy:</strong> {{.Replay.UnprotectedPath}}</li><li><strong>AgntID decision:</strong> {{.Replay.AgntIDDecision}}</li><li><strong>Protected outcome:</strong> {{.Replay.ProtectedOutcome}}</li></ol><p class="muted">{{.Replay.Disclaimer}}</p></details>{{end}}</article>{{else}}<p>No actionable findings were produced.</p>{{end}}
{{if eq .Kind "technical"}}
<section class="section"><h2>Identity exposure</h2><p class="muted">Catalog visibility is measured; tool executability is not tested.</p><table><thead><tr><th>Identity</th><th>Authentication</th><th>Status</th><th>Tools</th></tr></thead><tbody>{{range .Detail.IdentityExposure.Profiles}}<tr><td>{{.Label}}</td><td>{{.Authentication}}</td><td>{{.Status}}</td><td>{{.ToolCount}}</td></tr>{{end}}</tbody></table></section>
<section class="section"><h2>Tool intelligence</h2><table><thead><tr><th>Tool</th><th>Operation</th><th>Effects</th><th>Sensitivity</th><th>Visible to</th><th>Risk</th></tr></thead><tbody>{{range .Detail.Tools}}<tr><td>{{.Name}}</td><td>{{.Classification.OperationType}}</td><td>{{join .Classification.Effects}}</td><td>{{.Classification.Sensitivity}}</td><td>{{join .VisibleTo}}</td><td>{{upper .Risk}}</td></tr>{{end}}</tbody></table></section>
<section class="section"><h2>OWASP-aligned input and output trust boundaries</h2><p class="section-lead">Highlights where model-generated parameters or untrusted results can cross URL, filesystem, interpreter, query, credential, or follow-on action boundaries.</p><div class="why"><strong>How to read this:</strong> these are metadata-derived exposure signals. They do not prove that server-side validation or runtime enforcement is missing.</div><table><thead><tr><th>Tool</th><th>Agent-controlled input boundary</th><th>Output trust</th></tr></thead><tbody>{{range .Detail.Tools}}<tr><td>{{.Name}}</td><td>{{inputrisks .Schema.InputRisks}}</td><td>{{outputtrust .}}</td></tr>{{end}}</tbody></table></section>
<section class="section"><h2>Catalog drift</h2><p class="section-lead">Compares the current advertised tool catalog with the latest completed assessment of this target. It highlights tools that appeared, disappeared, or changed.</p><div class="why"><strong>Why it matters:</strong> a previously reviewed tool name can gain different inputs, behavior, or risk while an old policy decision remains in place.</div><p class="muted">Changes may come from a deployment, dynamic configuration, SDK update, or a different set of credentials and identity-visible tools.</p><div class="legend"><div><strong>High</strong><span>New high-impact capability, changed safety hints, or classification change.</span></div><div><strong>Medium</strong><span>Contract or selection behavior changed and needs review.</span></div><div><strong>Low</strong><span>A capability disappeared; dependent workflows may break.</span></div></div>{{if .Detail.CatalogDrift.Changes}}{{range .Detail.CatalogDrift.Changes}}<article class="change"><div class="change-head"><h3>{{.ToolName}}</h3><span class="badge">{{.ChangeType}}</span><span class="badge severity">{{upper .Severity}}</span></div><p>{{.Summary}}</p><div><strong>Changed fields:</strong> {{range .Fields}}<span class="pill">{{.}}</span>{{end}}</div><p><strong>Review focus:</strong> {{.PolicyImpact}}</p></article>{{end}}{{else}}{{if .Detail.CatalogDrift.Compared}}<div class="result good"><strong>No catalog changes detected</strong><span>The advertised tool declarations match the prior assessment.</span></div>{{else}}<div class="result"><strong>Baseline created</strong><span>No earlier completed assessment of this target was available. This catalog will be used for the next comparison.</span></div>{{end}}{{end}}<p class="muted">Drift describes declaration changes, not proof of malicious behavior or implementation changes.</p></section>
<section class="section"><h2>Metadata content integrity</h2><p class="section-lead">Reviews text an AI may read before any tool is called—server instructions, tool and schema descriptions, prompts, and resources—for deterministic patterns associated with instruction override, credential disclosure, tool redirection, or unintended data transfer.</p><div class="why"><strong>Why it matters:</strong> advertised metadata can influence tool choice and agent behavior before runtime policy evaluates a call. This is an indicator check, not a safety score.</div>{{range .Detail.ContentIntegrity.Signals}}<article class="finding {{.Severity}}"><div class="eyebrow">{{upper .Severity}} · {{.SurfaceKind}}</div><h3>{{.Title}}</h3><p>{{.Summary}}</p><p><strong>Surface:</strong> {{.SurfaceID}}</p><p><strong>Matched excerpt:</strong> {{.MatchedText}}</p></article>{{else}}<div class="result good"><strong>No deterministic warning patterns found</strong><span>Reviewed {{.Detail.ContentIntegrity.ItemsScanned}} advertised metadata surfaces. This does not prove that all content or runtime behavior is safe.</span></div>{{end}}</section>
<section class="section"><h2>Tool contract readiness</h2><p class="section-lead">Estimates how precisely each advertised tool can be selected, validated, and governed from the metadata available to an AI agent and policy engine.</p><div class="legend"><div><strong>Score</strong><span>Declaration quality from 0–100, based only on checks with evidence.</span></div><div><strong>Coverage</strong><span>Applicable checks the metadata could prove. Lower coverage means uncertainty, not failure.</span></div><div><strong>Grade</strong><span>Strong 85–100 · Developing 70–84 · Needs work below 70.</span></div></div><table><thead><tr><th>Tool</th><th>Score</th><th>Coverage</th><th>Grade</th></tr></thead><tbody>{{range .Detail.Readiness.Tools}}<tr><td>{{.ToolName}}</td><td>{{.Score}}/100</td><td>{{printf "%.0f" .Coverage}}%</td><td>{{.Grade}}</td></tr>{{end}}</tbody></table><p class="muted">{{.Detail.Readiness.Disclaimer}}</p></section>
{{if .Detail.RiskChains}}<section class="section"><h2>Capability risk chains</h2>{{range .Detail.RiskChains}}<article class="chain"><div class="eyebrow">{{upper .Severity}}</div><h3>{{.Title}}</h3><p>{{.Description}}</p><div>{{range .ToolNames}}<span class="pill">{{.}}</span>{{end}}</div></article>{{end}}</section>{{end}}
<section class="section"><h2>Evidence timeline</h2><table><thead><tr><th>Stage</th><th>Status</th><th>Duration</th></tr></thead><tbody>{{range .Detail.EngineRuns}}<tr><td>{{.Name}}</td><td>{{.Status}}</td><td>{{.DurationMs}} ms</td></tr>{{end}}</tbody></table></section>
{{end}}
<p class="muted">Generated by AgntID Observatory. No MCP tools were invoked during this assessment.</p></main></body></html>`))

type reportView struct {
	*domain.Assessment
	Detail     *domain.Assessment
	Dimensions []domain.DimensionScore
	Kind       string
}

func renderHTML(a *domain.Assessment, kind string) ([]byte, error) {
	var b bytes.Buffer
	err := htmlTemplate.Execute(&b, reportView{Assessment: a, Detail: a, Dimensions: orderedDimensions(a), Kind: kind})
	return b.Bytes(), err
}
func orderedDimensions(a *domain.Assessment) []domain.DimensionScore {
	order := []string{"security", "protocol", "ai-readiness", "operational"}
	out := make([]domain.DimensionScore, 0, 4)
	for _, key := range order {
		if d, ok := a.Scorecard.Dimensions[key]; ok {
			out = append(out, d)
		}
	}
	return out
}
