export type AssessmentStatus = "queued"|"running"|"completed"|"partial"|"failed"|"canceled";
export interface Target { protocol:string; url:string; host?:string }
export interface RiskProfile { critical:number; high:number; medium:number; low:number; info:number }
export interface DimensionScore { name:string; score:number; coverage:number; status:string; weight:number }
export interface Scorecard { overall:number; coverage:number; dimensions:Record<string,DimensionScore> }
export interface EngineRun { id:string; name:string; status:string; progress:number; message?:string; startedAt?:string; completedAt?:string; durationMs?:number }
export interface Recommendation { id:string; priority:string; title:string; detail:string; effort?:string }
export interface RuleReplay { title:string; trigger:string; unprotectedPath:string; agntidDecision:string; protectedOutcome:string }
export interface PolicyReplay extends RuleReplay { observed:string; toolNames:string[]; disclaimer:string }
export interface Finding { id:string; ruleId:string; category:string; severity:string; title:string; description:string; whyItMatters:string; recommendation:Recommendation; evidenceIds:string[]; confidence:number; provenance:string; penalty:number; dimension:string; references?:string[]; classification:string; toolNames:string[]; replay?:PolicyReplay }
export interface Evidence { id:string; kind:string; title:string; summary:string; data?:Record<string,unknown>; observation:{source:string;confidence:number;provenance:string;collectedAt:string} }
export interface ToolAnnotations { title?:string; readOnlyHint?:boolean; destructiveHint?:boolean; idempotentHint?:boolean; openWorldHint?:boolean }
export interface DimensionConfidence { band:string; score:number; evidence:string[] }
export interface ToolClassification { taxonomyVersion:number; classifierRevision:string; operationType:string; domain:string; blastRadius:string; sensitivity:string; criticality:string; privilegeLevel:number; isMutating:boolean; isDiscover:boolean; executionSurface:string; effects:string[]; confidenceBand:string; perDimensionConfidence:Record<string,DimensionConfidence>; evidence:string[]; annotationContradictions:string[] }
export interface SchemaSignal { code:string; severity:string; path?:string; message:string }
export interface InputRisk { kind:string; path:string; severity:string; reason:string; constrained:boolean }
export interface SchemaAnalysis { valid:boolean; hasOutputSchema:boolean; additionalProperties:string; propertyCount:number; requiredCount:number; describedPropertyCount:number; descriptionCoverage:number; maxDepth:number; unconstrainedStringCount:number; sensitiveFields:string[]; dangerousFields:string[]; inputRisks:InputRisk[]; signals:SchemaSignal[] }
export interface ToolPolicyDecision { profile:string; disposition:string; reasons:string[]; requiresApproval:boolean }
export interface ToolProfile { name:string; description?:string; inputSchema?:Record<string,unknown>; outputSchema?:Record<string,unknown>; annotations:ToolAnnotations; categories:string[]; risk:string; confidence:number; estimatedTokens:number; fingerprint:string; visibleTo:string[]; classification:ToolClassification; schema:SchemaAnalysis; policyPreview:Record<string,ToolPolicyDecision> }
export interface IdentityProfile { id:string; label:string; kind:string; status:string; authentication:string; toolCount:number; toolNames:string[]; catalogFingerprint?:string; error?:string }
export interface ToolExposure { toolName:string; visibleTo:string[]; hiddenFrom:string[]; catalogEquivalent:boolean }
export interface IdentityExposure { profiles:IdentityProfile[]; tools:ToolExposure[]; comparedProfiles:number; catalogEquivalent:boolean; privilegeSeparationObserved:boolean; anonymousToolCount:number; notes:string[] }
export interface PolicySimulationProfile { id:string; name:string; visibleCount:number; hiddenCount:number; approvalCount:number; visibleToolNames:string[]; hiddenToolNames:string[] }
export interface PolicySimulation { profiles:PolicySimulationProfile[]; generated:boolean; disclaimer:string }
export interface RiskChain { id:string; title:string; severity:string; description:string; toolNames:string[]; signals:string[] }
export interface ContentItem { kind:string; id:string; name?:string; text?:string; uri?:string; mimeType?:string; provenance:string }
export interface ContentSignal { id:string; ruleId:string; surfaceKind:string; surfaceId:string; severity:string; category:string; title:string; summary:string; matchedText?:string; recommendation:string; confidence:number; evidence:string[] }
export interface ContentIntegrityProfile { itemsScanned:number; signals:ContentSignal[]; bySeverity:Record<string,number>; disclaimer:string }
export interface ReadinessCheck { id:string; title:string; severity:string; status:string; evidence:string; recommendation?:string }
export interface ToolReadiness { toolName:string; score:number; coverage:number; grade:string; checks:ReadinessCheck[] }
export interface ReadinessProfile { tools:ToolReadiness[]; averageScore:number; coverage:number; disclaimer:string }
export interface CatalogChange { toolName:string; changeType:string; severity:string; summary:string; policyImpact:string; fields:string[]; previousFingerprint?:string; currentFingerprint?:string }
export interface CatalogDriftProfile { baselineAssessmentId?:string; baselineAt?:string; compared:boolean; stable:boolean; previousFingerprint?:string; currentFingerprint?:string; added:number; removed:number; modified:number; changes:CatalogChange[]; disclaimer:string }
export interface OAuthPosture { status:string; protected:boolean; challengePresent:boolean; resourceMetadataUrl?:string; resourceMetadataValid:boolean; resource?:string; authorizationServers:string[]; authorizationServerMetadataValid:boolean; issuer?:string; authorizationEndpoint?:string; tokenEndpoint?:string; registrationEndpoint?:string; dcrSupported:boolean; clientIdMetadataDocumentSupported:boolean; pkceS256:boolean; scopes:string[]; bearerMethods:string[]; headerBearerSupported:boolean; authorizationCompleted:boolean; registrationMethod?:string; authorizedIdentities:string[]; diagnostics:string[]; assessedAt?:string }
export interface OAuthSession { id:string; label:string; targetUrl:string; status:string; authorizationUrl?:string; profile:OAuthPosture; error?:string; createdAt:string; expiresAt:string }
export interface OfflineSnapshot { name:string; targetUrl?:string; serverInstructions?:string; server?:Partial<Assessment["server"]>; tools:Partial<ToolProfile>[]; prompts?:ContentItem[]; resources?:ContentItem[] }
export interface Artifact { id:string; name:string; format:string; kind:string; contentType:string; size:number; sha256:string; createdAt:string }
export interface AssessmentSummary { id:string; mode:string; target:Target; status:AssessmentStatus; connectionStatus:string; progress:number; overallScore:number; coverage:number; risk:RiskProfile; createdAt:string; completedAt?:string }
export interface Assessment extends Omit<AssessmentSummary,"overallScore"|"coverage"> { currentStage?:string; executiveSummary?:string; technicalSummary?:string; startedAt?:string; engineRuns:EngineRun[]; findings:Finding[]; evidence:Evidence[]; recommendations:Recommendation[]; artifacts:Artifact[]; tools:ToolProfile[]; identityExposure:IdentityExposure; policySimulation:PolicySimulation; riskChains:RiskChain[]; contentInventory:ContentItem[]; contentIntegrity:ContentIntegrityProfile; readiness:ReadinessProfile; catalogDrift:CatalogDriftProfile; oauth:OAuthPosture; server:{name?:string;version?:string;protocolVersion?:string;transport?:string;capabilities?:Record<string,unknown>;authentication:string;authorization:string;tls:string;toolCount:number;promptCount:number;resourceCount:number}; context:{toolTokens:number;promptTokens:number;resourceTokens:number;instructionTokens:number;totalTokens:number;contextWindow:number;utilization:number;estimator:string}; risk:RiskProfile; scorecard:Scorecard; facts?:Record<string,unknown>; error?:string }
export interface Rule { id:string; version:string; category:string; severity:string; dimension:string; penalty:number; title:string; description:string; whyItMatters:string; recommendation:string; references:string[]; tags:string[]; module:string; query:string; evidence:string[]; enabled:boolean; rego?:string; classification:string; replay?:RuleReplay }
export interface DashboardSummary { totalAssessments:number; averageScore:number; completed:number; risk:RiskProfile; modes:{live:number;sample:number;offline:number}; recent:AssessmentSummary[] }
